# Bilibili
BILIBILI_SEARCH_RESULTS_NUM = 1
WHISPER_MODEL_SIZE = "tiny"
BILIBILI_VIDEO_TRANSCRIPT_LENGTH_LIMIT = 10
BILIBILI_COMMENTS_MAX_NUM = 200
BILIBILI_COMMENTS_REQUEST_TIMEOUT_SECONDS = 20
BILIBILI_COMMENTS_MAX_CONCURRENT_REQUESTS = 5
BILIBILI_COMMENTS_COMMENT_PAGE_SIZE = 20
BILIBILI_COMMENTS_RETRY_DELAY_SECONDS = 3
BILIBILI_COMMENTS_MAX_RETRIES = 3
BILIBILI_COMMENTS_MAX_REPLIES_PER_COMMENT = 20
BILIBILI_COMMENTS_LENGTH_MIN = 40
BILIBILI_VIEW_API_URL = "https://api.bilibili.com/x/web-interface/view?bvid={bvid}"
BILIBILI_COMMENT_API_URL = "https://api.bilibili.com/x/v2/reply?type=1&oid={aid}&pn={page}&ps={size}&sort=2"
BILIBILI_SUB_COMMENT_API_URL = "https://api.bilibili.com/x/v2/reply/reply?type=1&oid={aid}&root={root_rpid}&pn={page}&ps={size}"

